version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express

  express:
    image: emon110852/express-app:v1.0
    ports:
      - "3000:5000"
